version: "3.8"

services:
  cookiecutter:
    container_name: cookiecutter-maker
    build:
      context: .
      dockerfile: Dockerfile.cookiecutter
    tty: true
    volumes:
      - ./:/boilerplate/template
      - ${FOLDER_DEST}:/boilerplate/tmp
