# Start from golang base image
FROM golang:alpine

# ENV GO111MODULE=on

# Add Maintainer info
LABEL maintainer="DUNA"

# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git

RUN apk add --no-cache bash curl

# Set the current working directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed
RUN go mod download

RUN go install github.com/canthefason/go-watcher/cmd/watcher

ENV GIN_MODE="debug"

ENV GIN_PORT=":80"

ENTRYPOINT ["watcher"]